name: Workflow Object for Project

on:
  push:
    branches:
      - main


jobs:
  check-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      # Installing python
      - run: echo Setting up python..
      - name: Set up Python 3.10.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.9

      # run test pipeline
      - run: echo Testing phase is starting..
      - name: Run test
        run: |
          chmod +x ./main/project/tests.sh && cd ./main && ./project/tests.sh
